<?php
namespace RoxAppointmentBooking\Modules\FrontendBookingPanel\REST;

use WP_REST_Request;
use WP_REST_Response;
use WP_Error;
use RoxAppointmentBooking\Supports\Abstracts\AbstractREST;

/**
 * Class ResetPasswordRequest
 *
 * @package RoxAppointmentBooking\Modules\FrontendBookingPanel\REST
 * @description Handles public customer "forgot password" requests by emailing a
 * password reset link to the account owner.
 */
class ResetPasswordRequest extends AbstractREST
{
    /**
     * Whether this REST endpoint should be loaded.
     *
     * @var bool
     */
    public static $loadable = true;

    /**
     * REST route for the reset-password request.
     *
     * @var string
     */
    public static string $route = '/public/customer/reset-password-request';

    /**
     * Human-readable route pattern used by the UI.
     *
     * @var string
     */
    public static string $usableRoute = '/public/customer/reset-password-request';

    /**
     * Get the HTTP methods allowed for this route.
     *
     * @return string|array
     */
    protected function getMethods(): string|array
    {
        return 'POST';
    }

    /**
     * Check whether the current user can access this endpoint.
     *
     * @param WP_REST_Request $request REST request instance.
     * @return bool
     */
    public function permissionCheck(WP_REST_Request $request): bool
    {
        return true;
    }

    /**
     * Handle the REST API request.
     *
     * @param WP_REST_Request $request REST request instance.
     * @return WP_REST_Response|WP_Error
     */
    public function handleRequest(WP_REST_Request $request): WP_REST_Response|WP_Error
    {
        $params = $request->get_params();

        if (empty($params['email'])) {
            $json_params = $request->get_json_params();
            if ($json_params) {
                $params = array_merge($params, $json_params);
            }
        }

        if (empty($params['email'])) {
            return new WP_REST_Response([
                'success' => false,
                'code' => 400,
                'message' => esc_html__('Email is required', 'rox-appointment-booking'),
                'data' => null
            ], 400);
        }

        $email = sanitize_email($params['email']);

        if (!is_email($email)) {
            return new WP_REST_Response([
                'success' => false,
                'code' => 400,
                'message' => esc_html__('Invalid email address', 'rox-appointment-booking'),
                'data' => null
            ], 400);
        }

        try {
            $wp_user = get_user_by('email', $email);

            // An unknown address gets the same answer as a known one: telling
            // the caller which is which lets anyone probe the site for the
            // email addresses that have accounts.
            if ($wp_user) {
                $reset_key = get_password_reset_key($wp_user);

                if (!is_wp_error($reset_key)) {
                    $reset_page_url = $this->resolveResetPageUrl($params['reset_page_url'] ?? '');

                    $this->sendResetEmail($wp_user, $reset_key, $reset_page_url);
                }
            }

            return new WP_REST_Response([
                'success' => true,
                'code' => 200,
                'message' => esc_html__('If an account exists for that email address, we have sent it a password reset link.', 'rox-appointment-booking'),
                'data' => null
            ], 200);
        } catch (\Exception $e) {
            return new WP_REST_Response([
                'success' => false,
                'code' => 500,
                'message' => $e->getMessage(),
                'data' => null
            ], 500);
        }
    }

    /**
     * Resolve the booking-panel page URL the reset link should point back to.
     *
     * Only same-site URLs are accepted (prevents the reset link from being
     * pointed at an external host). Falls back to the site home URL.
     *
     * @param string $reset_page_url URL supplied by the booking panel.
     * @return string
     */
    private function resolveResetPageUrl(string $reset_page_url): string
    {
        $reset_page_url = esc_url_raw(trim($reset_page_url));

        if (empty($reset_page_url)) {
            return home_url('/');
        }

        $requestHost = wp_parse_url($reset_page_url, PHP_URL_HOST);
        $siteHost = wp_parse_url(home_url('/'), PHP_URL_HOST);

        if (empty($requestHost) || strtolower($requestHost) !== strtolower((string) $siteHost)) {
            return home_url('/');
        }

        return $reset_page_url;
    }

    /**
     * Send the password reset link email to the account owner.
     *
     * @param \WP_User $wp_user        WordPress user account.
     * @param string   $reset_key      Password reset key generated by WordPress.
     * @param string   $reset_page_url Booking-panel page URL to link back to.
     * @return void
     */
    private function sendResetEmail(\WP_User $wp_user, string $reset_key, string $reset_page_url): void
    {
        // add_query_arg() URL-encodes the values itself, so pass them raw to
        // avoid double-encoding.
        $reset_url = add_query_arg(
            [
                'rox_reset_key' => $reset_key,
                'rox_reset_login' => $wp_user->user_login,
            ],
            $reset_page_url
        );

        $display_name = $wp_user->display_name ? $wp_user->display_name : $wp_user->user_login;

        do_action(
            'rox_appointment_booking_email_event',
            'password_reset',
            [
                'customer'         => [
                    'first_name' => $display_name,
                    'last_name'  => '',
                    'email'      => $wp_user->user_email,
                ],
                'username'         => $wp_user->user_login,
                'set_password_url' => $reset_url,
            ]
        );
    }
}
