<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit30d080dea556d63135534bdfb0a72b7c
{
    public static $files = array (
        'd92f49fe138fde4e7a3ec6f988960524' => __DIR__ . '/..' . '/stripe/stripe-php/lib/version_check.php',
    );

    public static $prefixLengthsPsr4 = array (
        'R' => 
        array (
            'RoxAppointmentBooking\\' => 22,
            'RoxAppointmentBookingVendors\\Stripe\\' => 36,
            'RoxAppointmentBookingVendors\\Bamarni\\Composer\\Bin\\' => 50,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'RoxAppointmentBooking\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
        'RoxAppointmentBookingVendors\\Stripe\\' => 
        array (
            0 => __DIR__ . '/..' . '/stripe/stripe-php/lib',
        ),
        'RoxAppointmentBookingVendors\\Bamarni\\Composer\\Bin\\' => 
        array (
            0 => __DIR__ . '/..' . '/bamarni/composer-bin-plugin/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit30d080dea556d63135534bdfb0a72b7c::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit30d080dea556d63135534bdfb0a72b7c::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit30d080dea556d63135534bdfb0a72b7c::$classMap;

        }, null, ClassLoader::class);
    }
}
